global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-chat'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']      # Spring Boot Actuator

  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9100']      # Node Exporter