name: CI/CD to Koyeb

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build JAR with Maven
        run: ./mvnw clean package -DskipTests

      - name: Deploy to Koyeb
        uses: koyeb/koyeb-deploy-action@v1
        with:
          token: ${{ secrets.KOYEB_API_TOKEN }}
          app-name: chat-app
          service-name: chat-service
          dockerfile: ./Dockerfile
